"""Archive true-format masters and embed AI-provenance metadata in derived PNGs.

  python3 scripts/cast-provenance.py
"""
import os, shutil, subprocess
from PIL import Image, PngImagePlugin

G = 'generated-images'
ARCHIVE = 'generated-images/masters-archive'
CAST = ['pulsar','voyager','sentinel','nova','nebula','echo','atlas','iris','meridian','vector']
VER = 'v8'
MODEL = 'gemini-3-pro-image'
os.makedirs(ARCHIVE, exist_ok=True)

def kind(p):
    d = open(p, 'rb').read(8)
    if d[:8] == b'\x89PNG\r\n\x1a\n': return 'png'
    if d[:2] == b'\xff\xd8': return 'jpg'
    return 'bin'

print(f'{"drone":10}{"master true fmt":>17}{"archived as":>34}')
for n in CAST:
    src = f'{G}/{n}-android-{VER}.png'
    if not os.path.exists(src):
        print(f"{n:22}  no render — skipped")
        continue
    k = kind(src)
    dst = f'{ARCHIVE}/{n}-android-{VER}-master.{k}'
    shutil.copy2(src, dst)          # byte-identical: signed manifest intact
    print(f'{n:10}{k:>17}{os.path.basename(dst):>34}')

print('\nEmbedding provenance into aligned PNGs:')
for n in CAST:
    p = f'{G}/{n}-android-{VER}-aligned.png'
    im = Image.open(p).convert('RGB')
    meta = PngImagePlugin.PngInfo()
    meta.add_text('Software', f'Generated by Google {MODEL}')
    meta.add_text('Source', 'trainedAlgorithmicMedia')
    meta.add_text('digitalSourceType',
                  'http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia')
    meta.add_text('Description',
                  'AI-generated synthetic portrait. Fictional character; not a real person '
                  'and not modelled on any identifiable individual.')
    meta.add_text('ArchivalOriginal', f'masters-archive/{n}-android-{VER}-master.{kind(f"{G}/{n}-android-{VER}.png")}')
    meta.add_text('OriginalCredential',
                  'Signed C2PA/SynthID manifest retained on the archival original; '
                  'not transferable through re-encode.')
    im.save(p, 'PNG', pnginfo=meta)

ok = 0
for n in CAST:
    d = open(f'{G}/{n}-android-{VER}-aligned.png', 'rb').read()
    if b'trainedAlgorithmicMedia' in d and b'gemini-3-pro-image' in d:
        ok += 1
print(f'\naligned PNGs now declaring AI provenance: {ok}/{len(CAST)}')
arch = sum(1 for n in CAST for e in ('jpg','png')
           if os.path.exists(f'{ARCHIVE}/{n}-android-{VER}-master.{e}'))
print(f'archival masters with signed manifest intact: {arch}/{len(CAST)}')
